### ISSUE TITLE
no `Svg` `SvgData` in `widget`

### ISSUE THREAD

**Issue by NatsuShio** [linebender/druid#1862]
Referring to the toml file in the example, I think it only needs to add a reference to "usvg", but why can't I find the compile time prompt?

main file.
```rust
use druid::{widget::{FillStrat, Flex, Svg, SvgData, WidgetExt}, AppLauncher, LocalizedString, Widget, WindowDesc, Color};
use druid::widget::{Button, Container};

fn main() {
    let main_window = WindowDesc::new(ui_builder)
        .window_size((960.0, 580.0))
        .set_position((1024.0, 960.0));
    let data = 0_u32;
    AppLauncher::with_window(main_window)
        .use_simple_logger()
        .launch(data)
        .expect("launch failed");
}

fn ui_builder() -> impl Widget<u32> {
    let browse_svg = match include_str!("./assets/browse.svg").parse::<SvgData>() {
        Ok(svg) => svg,
        Err(err) => {
            // error!("{}", err);
            // error!("Using an empty SVG instead.");
            SvgData::default()
        }
    };

    // The label text will be computed dynamically based on the current locale and count
    let text =
        LocalizedString::new("hello-counter").with_arg("count", |data: &u32, _env| (*data).into());
    let svg = Svg::new(browse_svg).padding(5.0).center();
    let button = Button::new("increment")
        .on_click(|_ctx, data, _env| *data += 1)
        .padding(5.0);

    let container_menu = Container::new(svg).background(Color::WHITE);

    Flex::row()
        .with_child(container_menu)
        //.with_child(label)
        .with_child(button)
}
```

cargo.toml
```toml
[package]
name = "IndexJi"
version = "0.1.0"
authors = ["me"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"
druid-shell = "0.7.0"
druid-derive = "0.4.0"
rusqlite = "0.25.3"

usvg =  "0.14.1"
harfbuzz-sys =  "0.4.0"
```

error is
```log
error[E0432]: unresolved imports `druid::widget::Svg`, `druid::widget::SvgData`
 --> src\main.rs:1:39
  |
1 | use druid::{widget::{FillStrat, Flex, Svg, SvgData, WidgetExt}, AppLauncher, LocalizedString, Widget, WindowDesc, Color};
  |                                       ^^^  ^^^^^^^ no `SvgData` in `widget`
  |                                       |
  |                                       no `Svg` in `widget`
```
