### ISSUE TITLE
Scrollbar animation causing full-frame refresh

### ISSUE THREAD

**Issue by maxwell8888** [linebender/druid#2205]
Further to [this Zulip topic](https://xi.zulipchat.com/#narrow/stream/255910-druid-help/topic/Scroll.20in.20Either.20unexpected.20behaviour), I have an example where the scrollbar fade animation of a `Scroll` inside of an `Either` is causing another widget to paint. The problem is fixed by removing the Either wrapper. I'm using the master branch and running on Ubuntu 20.04.
```rust
use druid::widget::{Either, Flex, Painter, Scroll};
use druid::{AppLauncher, Data, WidgetExt, WindowDesc};

#[derive(Clone, Data)]
struct AppData;

fn main() {
    let widget = Flex::row()
        .with_child(Either::new(
            |_, _| true,
            Scroll::new(Flex::column().fix_size(300., 9999.)),
            Flex::column(),
        ))
        .with_child(Painter::new(|_, _, _| println!("paints")));
    let window = WindowDesc::new(widget);
    AppLauncher::with_window(window).launch(AppData {}).unwrap();
}
```
Cargo.toml
```toml
[package]
name = "rust_playground"
version = "0.1.0"
edition = "2021"

[dependencies]
druid = { git = "https://github.com/linebender/druid" }
```
